name: Update images and commit

on: 
  schedule:
    - cron: '0,15,30,45 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run "npm install"
      uses: elstudio/actions-js-build/build@v2
      with:
        args: "install"

    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v3
      with:
        commitMessage: Update files
